"""PIMX: Peer Introduction and Manifest Exchange.

A hubless HTTPS federation protocol for directory nodes (ADR-005).
"""

from .client import (
    SIGNATURE_HEADER,
    FederationClient,
    MissingCapabilitySummaryEndpointError,
    ManifestVerificationError,
    MissingRevocationsEndpointError,
    ResponseSignatureError,
)
from .admission import (
    AdmissionDecision,
    AdmissionPolicy,
    EvidenceVerifier,
    KeyContinuityDecision,
    KeyContinuityPolicy,
    admit_manifest,
    check_key_continuity,
    domain_evidence_verifier,
)
from .audit import audit_record
from .crypto import (
    JWK,
    b64u_decode,
    b64u_encode,
    canonical_bytes,
    generate_key,
    public_jwk,
    public_key_from_jwk,
)
from .discovery import (
    DiscoveryOutcome,
    DiscoveryRefreshReport,
    refresh_discovered_members,
)
from .health import PeerHealthProbeResult, probe_peer_health
from .membership import (
    DisclosurePolicy,
    MemberRecord,
    MembershipTable,
    PeerState,
    apply_revocation_notice,
    disclose_members,
)
from .net import SSRFError
from .models import (
    AdmissionEvidence,
    CapabilitySummary,
    Disclosure,
    DomainProofEvidence,
    GenericAdmissionEvidence,
    HealthResponse,
    IntroduceRequest,
    IntroduceResponse,
    Manifest,
    ManifestLimits,
    MemberRef,
    Membership,
    MembersResponse,
    ProtocolResponse,
    PublicKey,
    RevocationNotice,
    RevocationsResponse,
    Signature,
    SignedRequest,
)
from .protocols import (
    MembershipStore,
    NonceCache,
    RateLimiter,
    TokenBucketRateLimiter,
)
from .refresh import ManifestRefreshDecision, refresh_peer_manifest
from .signing import (
    build_signed_request,
    check_body_size,
    check_manifest,
    find_jwk,
    sha256_hex,
    sign_dict,
    sign_manifest,
    sign_model,
    verify_dict,
    verify_manifest,
    verify_model,
    verify_response_signature,
    verify_revocation_notice,
    verify_signed_request,
)

__all__ = [
    "FederationClient",
    "MissingCapabilitySummaryEndpointError",
    "ManifestVerificationError",
    "MissingRevocationsEndpointError",
    "ResponseSignatureError",
    "SIGNATURE_HEADER",
    "SSRFError",
    "AdmissionDecision",
    "AdmissionPolicy",
    "admit_manifest",
    "check_key_continuity",
    "domain_evidence_verifier",
    "KeyContinuityDecision",
    "KeyContinuityPolicy",
    "audit_record",
    "JWK",
    "b64u_decode",
    "b64u_encode",
    "canonical_bytes",
    "generate_key",
    "public_jwk",
    "public_key_from_jwk",
    "DiscoveryOutcome",
    "DiscoveryRefreshReport",
    "refresh_discovered_members",
    "PeerHealthProbeResult",
    "probe_peer_health",
    "DisclosurePolicy",
    "MemberRecord",
    "MembershipTable",
    "PeerState",
    "apply_revocation_notice",
    "disclose_members",
    "AdmissionEvidence",
    "CapabilitySummary",
    "Disclosure",
    "DomainProofEvidence",
    "GenericAdmissionEvidence",
    "HealthResponse",
    "IntroduceRequest",
    "IntroduceResponse",
    "Manifest",
    "ManifestLimits",
    "MemberRef",
    "Membership",
    "MembersResponse",
    "ProtocolResponse",
    "PublicKey",
    "RevocationNotice",
    "RevocationsResponse",
    "Signature",
    "SignedRequest",
    "EvidenceVerifier",
    "MembershipStore",
    "NonceCache",
    "RateLimiter",
    "TokenBucketRateLimiter",
    "ManifestRefreshDecision",
    "refresh_peer_manifest",
    "build_signed_request",
    "check_body_size",
    "check_manifest",
    "find_jwk",
    "sha256_hex",
    "sign_dict",
    "sign_manifest",
    "sign_model",
    "verify_dict",
    "verify_manifest",
    "verify_model",
    "verify_response_signature",
    "verify_revocation_notice",
    "verify_signed_request",
]
