"""Federlet.

A framework-neutral HTTPS federation protocol library.
"""

from .admission import (
    AdmissionDecision,
    AdmissionPolicy,
    AuthMethodVerifier,
    EvidenceVerifier,
    KeyContinuityDecision,
    KeyContinuityPolicy,
    admit_manifest,
    check_key_continuity,
    domain_evidence_verifier,
)
from .audit import audit_record
from .bootstrap import (
    SeedBootstrapOutcome,
    SeedBootstrapReport,
    bootstrap_from_seeds,
)
from .certauth import (
    CertificateIdentity,
    CertVerifiedPeer,
    UnauthorizedCertificateIdentity,
    certificate_thumbprint,
    verify_certificate_identity,
)
from .client import (
    SIGNATURE_HEADER,
    FederationClient,
    ManifestVerificationError,
    MissingRevocationsEndpointError,
    ResponseSignatureError,
)
from .crypto import (
    JWK,
    b64u_decode,
    b64u_encode,
    canonical_bytes,
    generate_key,
    public_jwk,
    public_key_from_jwk,
)
from .discovery import (
    DiscoveryOutcome,
    DiscoveryRefreshReport,
    refresh_discovered_members,
)
from .health import PeerHealthProbeResult, probe_peer_health
from .membership import (
    DisclosurePolicy,
    MemberRecord,
    MembershipTable,
    PeerState,
    apply_revocation_notice,
    disclose_members,
)
from .models import (
    AdmissionEvidence,
    Disclosure,
    DomainProofEvidence,
    GenericAdmissionEvidence,
    HealthResponse,
    IntroduceRequest,
    IntroduceResponse,
    Manifest,
    ManifestLimits,
    MemberRef,
    Membership,
    MembersResponse,
    ProtocolResponse,
    PublicKey,
    RevocationNotice,
    RevocationsResponse,
    Signature,
    SignedRequest,
)
from .net import SSRFError
from .node import FederationNode
from .operations import (
    OperationItem,
    OperationRequest,
    OperationResponse,
    PayloadProvenance,
    build_operation_item,
    sign_operation_item,
    sign_operation_payload,
    verify_operation_item,
)
from .protocols import (
    MembershipStore,
    NonceCache,
    RateLimiter,
    TokenBucketRateLimiter,
)
from .publication import build_signed_manifest
from .refresh import ManifestRefreshDecision, refresh_peer_manifest
from .responses import (
    sign_introduce_response,
    sign_members_response,
    sign_operation_response,
    sign_revocations_response,
)
from .signing import (
    UnauthorizedPeerRequest,
    VerifiedPeer,
    build_signed_request,
    check_body_size,
    check_manifest,
    find_jwk,
    sha256_hex,
    sign_dict,
    sign_manifest,
    sign_model,
    verify_dict,
    verify_manifest,
    verify_model,
    verify_peer_request,
    verify_response_signature,
    verify_revocation_notice,
    verify_signed_request,
)
from .urls import well_known_url

__all__ = [
    "FederationClient",
    "ManifestVerificationError",
    "MissingRevocationsEndpointError",
    "ResponseSignatureError",
    "SIGNATURE_HEADER",
    "SSRFError",
    "FederationNode",
    "AdmissionDecision",
    "AdmissionPolicy",
    "AuthMethodVerifier",
    "admit_manifest",
    "check_key_continuity",
    "domain_evidence_verifier",
    "KeyContinuityDecision",
    "KeyContinuityPolicy",
    "audit_record",
    "CertificateIdentity",
    "CertVerifiedPeer",
    "UnauthorizedCertificateIdentity",
    "certificate_thumbprint",
    "verify_certificate_identity",
    "SeedBootstrapOutcome",
    "SeedBootstrapReport",
    "bootstrap_from_seeds",
    "JWK",
    "b64u_decode",
    "b64u_encode",
    "canonical_bytes",
    "generate_key",
    "public_jwk",
    "public_key_from_jwk",
    "DiscoveryOutcome",
    "DiscoveryRefreshReport",
    "refresh_discovered_members",
    "PeerHealthProbeResult",
    "probe_peer_health",
    "DisclosurePolicy",
    "MemberRecord",
    "MembershipTable",
    "PeerState",
    "apply_revocation_notice",
    "disclose_members",
    "AdmissionEvidence",
    "Disclosure",
    "DomainProofEvidence",
    "GenericAdmissionEvidence",
    "HealthResponse",
    "IntroduceRequest",
    "IntroduceResponse",
    "Manifest",
    "ManifestLimits",
    "MemberRef",
    "Membership",
    "MembersResponse",
    "ProtocolResponse",
    "PublicKey",
    "RevocationNotice",
    "RevocationsResponse",
    "Signature",
    "SignedRequest",
    "EvidenceVerifier",
    "MembershipStore",
    "NonceCache",
    "RateLimiter",
    "TokenBucketRateLimiter",
    "build_signed_manifest",
    "OperationItem",
    "OperationRequest",
    "OperationResponse",
    "PayloadProvenance",
    "build_operation_item",
    "sign_operation_item",
    "sign_operation_payload",
    "verify_operation_item",
    "ManifestRefreshDecision",
    "refresh_peer_manifest",
    "sign_introduce_response",
    "sign_members_response",
    "sign_operation_response",
    "sign_revocations_response",
    "build_signed_request",
    "check_body_size",
    "check_manifest",
    "find_jwk",
    "sha256_hex",
    "sign_dict",
    "sign_manifest",
    "sign_model",
    "verify_dict",
    "verify_manifest",
    "verify_model",
    "UnauthorizedPeerRequest",
    "VerifiedPeer",
    "verify_peer_request",
    "verify_response_signature",
    "verify_revocation_notice",
    "verify_signed_request",
    "well_known_url",
]
